version: "3.8"

networks:  
  iot-mobile-backend-network:  
    name: iot-mobile-backend-network  
    driver: bridge

services:
  iot-mobile-backend:
      build:
        context: ./backend/iot_mobile
        dockerfile: Dockerfile
      networks:
        - iot-mobile-backend-network
      ports:
        - "8080:8080"
      expose:
        - "8080"
