version: "3.8"

networks:
  iot-mobile-backend-network:
    name: iot-mobile-backend-network
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    env_file:
      - dev.env
    networks:
      - iot-mobile-backend-network
    ports:
      - "5432:5432"
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - dev.env
    networks:
      - iot-mobile-backend-network
    expose:
      - "5672"
      - "15672"
      
  iot-mobile-backend:
    build:
      context: ./backend/iot_mobile
      dockerfile: Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    restart: always
    networks:
      - iot-mobile-backend-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - dev.env
    depends_on:
      - db
      - rabbitmq
