version: "3.8"

networks:  
  iot-mobile-backend-network:  
    name: iot-mobile-backend-network  
    driver: bridge

services:
  iot-mobile-backend:
      build:
        context: ./backend/iot_mobile
        dockerfile: Dockerfile
      networks:
        - iot-mobile-backend-network
      ports:
        - "8080:8080"
      expose:
        - "8080"
      env_file:
        - dev.env
      environment:
        - SPRING_RABBITMQ_HOST=rabbitmq
      depends_on:
        - db
        - rabbitmq

  db:
    image: postgres
    restart: always
    env_file:
      - dev.env
    networks:
      - iot-mobile-backend-network
    ports:
      - "5432:5432"
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"