version: '3.3'

services:
  #service 1: definition of mysql database
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  #service 3: definition of your spring-boot app
  iot_mobile:                        #name of the image after dockerfile executes
    container_name: iot-mobile-backend  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:                           #define dependencies of this app
      - rabbitmq                                #dependency name (which is defined with this name 'db' in this file earlier)